name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y etiquetar la imagen de Docker
      - name: Build and tag Docker image
        run: |
          docker build -t nahuel277/web-app:latest .
          docker tag nahuel277/web-app:latest nahuel277/web-app:${{ github.run_id }}

      # Subir la imagen a DockerHub
      - name: Push Docker image
        run: |
          docker push nahuel277/web-app:latest
          docker push nahuel277/web-app:${{ github.run_id }}
