name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout source code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag Backend Docker image
      - name: Build and tag Backend Docker image
        run: |
          docker build -t nahuel277/backend:latest -f Backend/Dockerfile Backend
          docker tag nahuel277/backend:latest nahuel277/backend:${{ github.run_id }}

      # Push Backend Docker image to DockerHub
      - name: Push Backend Docker image
        run: |
          docker push nahuel277/backend:latest
          docker push nahuel277/backend:${{ github.run_id }}

      # Build and tag Frontend Docker image
      - name: Build and tag Frontend Docker image
        run: |
          docker build -t nahuel277/frontend:latest -f Frontend/Dockerfile Frontend
          docker tag nahuel277/frontend:latest nahuel277/frontend:${{ github.run_id }}

      # Push Frontend Docker image to DockerHub
      - name: Push Frontend Docker image
        run: |
          docker push nahuel277/frontend:latest
          docker push nahuel277/frontend:${{ github.run_id }}

